### ISSUE TITLE
CRITICAL Program: System.Exception: XOpenDisplay failed

### ISSUE THREAD

**Issue by nidkil** [zkSNACKs/WasabiDoc#126]
Hi,

I have installed Wasabi Wallet on Manjaro 18.0.4 and I'm getting the following error when starting ` ./wassabee`:

```
[nidkil@nidkil-manjaro WasabiLinux-1.1.6]$ ./wassabee 
2019-08-09 02:49:27 INFO 1c18b5fb-e097-4621-b688-f9a37c89228a: Wasabi GUI is starting...
2019-08-09 02:49:27 CRITICAL Program: System.Exception: XOpenDisplay failed
   at Avalonia.X11.AvaloniaX11Platform.Initialize(X11PlatformOptions options)
   at Avalonia.Controls.AppBuilderBase`1.Setup()
   at Avalonia.Controls.AppBuilderBase`1.Start[TMainWindow](Func`1 dataContextProvider)
   at WalletWasabi.Gui.Program.Main(String[] args)
2019-08-09 02:49:27 INFO 1c18b5fb-e097-4621-b688-f9a37c89228a: Wasabi GUI stopped gracefully.

Unhandled Exception: System.Exception: XOpenDisplay failed
   at Avalonia.X11.AvaloniaX11Platform.Initialize(X11PlatformOptions options)
   at Avalonia.Controls.AppBuilderBase`1.Setup()
   at Avalonia.Controls.AppBuilderBase`1.Start[TMainWindow](Func`1 dataContextProvider)
   at WalletWasabi.Gui.Program.Main(String[] args)
   at WalletWasabi.Gui.Program.Main(String[] args)
   at WalletWasabi.Gui.Program.<Main>(String[] args)
Aborted (core dumped)
```

Any suggestions how to solve this?

**Comment by yahiheb** [comment]
I think the right place for this issue is Wasabi Wallet's main [repository](https://github.com/zkSNACKs/WalletWasabi). Ask your question [here](https://github.com/zkSNACKs/WalletWasabi/issues).
This repository is better suited for documentation related issues.

**Comment by MaxHillebrand** [comment]
Yes, @yahiheb is right.

Sorry for confusing you with our github structure @nidkil, but can you please open the same issue in the main repo?

We're figuring out how to be more precise with which repo is for what.
I'm closing this issue now.
